CarsInventory.Web/Controllers/CarsController.cs
using CarsInventory.Data;
using CarsInventory.Repository;
using CarsInventory.Web.Utilities;
using Microsoft.AspNet.Identity;
using System;
using System.Net;
using System.Web.Mvc;

namespace CarsInventory.Web.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {
        private UnitOfWork unitOfWork;
        public CarsController()
        {
            unitOfWork = new UnitOfWork();
        }
        // GET: Cars
        public ActionResult Index()
        {
            return View(unitOfWork.CarsInventoryRepository.GetAll(User.Identity.GetUserId()));
        }

        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Brand,Model,Year,Price,New")] Car car)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Log.Info("Add Car started");

                    car.UserId = User.Identity.GetUserId();
                    unitOfWork.CarsInventoryRepository.Save(car);

                    Log.Info("Add Car completed");

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    Log.Error("Error occurred while adding Car", ex);
                }
            }

            return View(car);
        }

        public ActionResult Edit(int id)
        {

            if (id == null)
            {
                Log.Error("Edit Car: Bad request");
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = unitOfWork.CarsInventoryRepository.Get(id);

            if (car == null)
            {
                Log.Warn("Edit Car: Not found");
                return HttpNotFound();
            }
            
            
            return PartialView(car);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Brand,Model,Year,Price,New,UserId")] Car car)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Log.Info("Edit Car started");

                    unitOfWork.CarsInventoryRepository.Save(car);
                    Log.Info("Edit Car completed");

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    Log.Error("Error occurred while editing Car", ex);
                }
            }
            return View(car);
        }



    }
}

CarsInventory.Web/Views/Cars/Create.cshtml
@model CarsInventory.Data.Car

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.New, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.New)
                    @Html.ValidationMessageFor(model => model.New, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarsInventory.Web/Views/Cars/Edit.cshtml
@model CarsInventory.Data.Car

@{
    ViewBag.Title = "Edit";
}

@using (Ajax.BeginForm("Edit", "Cars", new AjaxOptions { HttpMethod = "Post" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(u => u.UserId)

    <div class="modal-header">
        <h4 class="modal-title">Edit Car</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    </div>
    <div class="modal-body">

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.New, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox" style="margin-left: 20px;">
                    @Html.EditorFor(model => model.New)
                    @Html.ValidationMessageFor(model => model.New, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
        <input type="submit" class="btn btn-info" value="Save">
    </div>
}

CarsInventory.Web/Views/Cars/Index.cshtml
@model IEnumerable<CarsInventory.Data.Car>

@{
    ViewBag.Title = "Index";
}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="table-wrapper">
    <div class="table-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Manage <b>Cars</b></h2>
            </div>
            <div class="col-sm-6">
                <a href="#addCarModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Add New Car</span></a>
            </div>
        </div>
    </div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Brand</th>
                <th>Model</th>
                <th>Year</th>
                <th>Price</th>
                <th>New</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Brand)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Year)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.New)
                    </td>
                    <td>
                        <a href="#" class="edit" onclick="editCar(@item.Id)"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<!-- Edit Modal HTML -->
<div id="addCarModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (Ajax.BeginForm("Create", "Cars", new AjaxOptions { HttpMethod = "Post" }))
            {
                @Html.AntiForgeryToken()
                <div class="modal-header">
                    <h4 class="modal-title">Add Car</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="control-label col-md-2" for="Brand">Brand</label>
                        <div class="col-md-10">
                            <input class="form-control text-box single-line" data-val="true" data-val-length="The field Brand must be a string with a maximum length of 256." data-val-length-max="256" data-val-required="The Brand field is required." id="Brand" name="Brand" type="text" value="">
                            <span class="field-validation-valid text-danger" data-valmsg-for="Brand" data-valmsg-replace="true"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2" for="Model">Model</label>
                        <div class="col-md-10">
                            <input class="form-control text-box single-line" data-val="true" data-val-length="The field Model must be a string with a maximum length of 100." data-val-length-max="100" data-val-required="The Model field is required." id="Model" name="Model" type="text" value="">
                            <span class="field-validation-valid text-danger" data-valmsg-for="Model" data-valmsg-replace="true"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2" for="Year">Year</label>
                        <div class="col-md-10">
                            <input class="form-control text-box single-line" data-val="true" data-val-number="The field Year must be a number." data-val-required="The Year field is required." id="Year" name="Year" type="number" value="">
                            <span class="field-validation-valid text-danger" data-valmsg-for="Year" data-valmsg-replace="true"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2" for="Price">Price</label>
                        <div class="col-md-10">
                            <input class="form-control text-box single-line" data-val="true" data-val-number="The field Price must be a number." data-val-required="The Price field is required." id="Price" name="Price" type="text" value="">
                            <span class="field-validation-valid text-danger" data-valmsg-for="Price" data-valmsg-replace="true"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2" for="New">New</label>
                        <div class="col-md-10">
                            <div class="checkbox" style="margin-left: 20px;">
                                <input class="check-box" data-val="true" data-val-required="The New field is required." id="New" name="New" type="checkbox" value="true"><input name="New" type="hidden" value="false">
                                <span class="field-validation-valid text-danger" data-valmsg-for="New" data-valmsg-replace="true"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-success" value="Add">
                </div>
            }
            
        </div>
    </div>
</div>
<!-- Edit Modal HTML -->
<div id="editCarModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            
        </div>
    </div>
</div>

@section scripts
{
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            //Setting up Data table
            $("table").DataTable({
                "columnDefs": [
                    { "width": "20%", "targets": 0 },
                    { "width": "20%", "targets": 1 },
                    { "width": "20%", "targets": 2 },
                    { "width": "20%", "targets": 3 },
                    { "width": "20%", "targets": 4 },
                    { "searchable": true, "targets": 0 },
                    { "searchable": true, "targets": 1 },
                    { "searchable": false, "targets": 2 },
                    { "searchable": false, "targets": 3 },
                    { "searchable": false, "targets": 4 }
                ],
                "paging": false,
                "info": false
            });

            // Activate tooltip
            $('[data-toggle="tooltip"]').tooltip();

        });
        function editCar(id) {
                var editUrl = "@Url.Action("Edit", "Cars")";
                $.ajax({
                    url: editUrl + "/" + id,
                    success: function (data) {
                        $('#editCarModal').find("div.modal-content").html(data); 
                        $('#editCarModal').modal();
                    }
                });
            }
    </script>
}